
server:
  port: 5004
  servlet:
    context-path: /api/v1

spring:
  application:
    name: location-service

  datasource:
    url: jdbc:mysql://localhost:3306/airline_location_db
    username: root
    password: Suman2058/03/29
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

